//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATC.CLN.CDP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDATCEntities : DbContext
    {
        public BDATCEntities()
            : base("name=BDATCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADICIONA> ADICIONA { get; set; }
        public virtual DbSet<ALUNO> ALUNO { get; set; }
        public virtual DbSet<ARQUIVO> ARQUIVO { get; set; }
        public virtual DbSet<ATIVIDADE> ATIVIDADE { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<PESSOA> PESSOA { get; set; }
    }
}
