//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO
    {
        public string dtConclusao { get; set; }
        public Nullable<int> creditos { get; set; }
        public int codAluno { get; set; }
        public string matricula { get; set; }
        public Nullable<int> codPessoa { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
    }
}
