//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATIVIDADE
    {
        public Nullable<int> valorCredito { get; set; }
        public string anoRegistro { get; set; }
        public int codAtividade { get; set; }
        public string tipoAtividade { get; set; }
        public Nullable<int> codCat { get; set; }
        public Nullable<bool> ativado { get; set; }
        public string unidAvali { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
